{% set version = "3.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-backbone
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/backbone_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/backbone/backbone_{{ version }}.tar.gz
  sha256: 18a4c5b314f8e558822f0440fcdf1bc7c838299c76c089f5bc681de35b9f94f0

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-igraph
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-igraph

test:
  commands:
    - $R -e "library('backbone')"           # [not win]
    - "\"%R%\" -e \"library('backbone')\""  # [win]

about:
  home: https://www.zacharyneal.com/backbone, https://github.com/domagal9/backbone
  license: GPL-3.0-only
  summary: Provides methods for extracting from a weighted graph a binary or signed backbone that retains only the significant edges. The user may input a weighted graph, or a bipartite graph from which a weighted graph is first constructed via projection. Backbone extraction methods include the stochastic degree sequence
    model (SDSM; Neal, Z. P. (2014). <doi:10.1016/j.socnet.2014.06.001>), the fixed degree sequence model (FDSM; Zweig, K. A., and Kaufmann, M. (2011). <doi:10.1007/s13278-011-0021-0>), the fixed row model (FRM; Neal, Z. P. (2013). <doi:10.1007/s13278-013-0107-y>), the fixed column model (FCM; Neal, Domagalski, and Sagan
    (2021). <arXiv:2105.13396>), the fixed fill model (FFM; Neal, Domagalski, and Sagan (2021). <arXiv:2105.13396>), and a universal threshold method.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: backbone
# Type: Package
# Title: Extracts the Backbone from Weighted Graphs
# Version: 1.5.0
# Authors@R: c( person("Zachary", "Neal", email = "zpneal@msu.edu", role = c("aut", "cre")), person("Rachel", "Domagalski", email = "domagal9@msu.edu", role = "aut"), person("Bruce", "Sagan", email = "bsagan@msu.edu", role = "aut"))
# Description: Provides methods for extracting from a weighted graph a binary or signed backbone that retains only the significant edges. The user may input a weighted graph, or a bipartite graph from which a weighted graph is first constructed via projection. Backbone extraction methods include the stochastic degree sequence model (SDSM; Neal, Z. P. (2014). <doi:10.1016/j.socnet.2014.06.001>), the fixed degree sequence model (FDSM; Zweig, K. A., and Kaufmann, M. (2011). <doi:10.1007/s13278-011-0021-0>), the fixed row model (FRM; Neal, Z. P. (2013). <doi:10.1007/s13278-013-0107-y>), the fixed column model (FCM; Neal, Domagalski, and Sagan (2021). <arXiv:2105.13396>), the fixed fill model (FFM; Neal, Domagalski, and Sagan (2021). <arXiv:2105.13396>), and a universal threshold method.
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Depends: R (>= 2.10)
# Imports: Matrix, methods, stats, utils, igraph, network, PoissonBinomial
# Suggests: knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# URL: https://www.zacharyneal.com/backbone, https://github.com/domagal9/backbone
# BugReports: https://github.com/domagal9/backbone/issues
# NeedsCompilation: no
# Packaged: 2021-06-03 17:26:45 UTC; zacharyneal
# Author: Zachary Neal [aut, cre], Rachel Domagalski [aut], Bruce Sagan [aut]
# Maintainer: Zachary Neal <zpneal@msu.edu>
# Repository: CRAN
# Date/Publication: 2021-06-04 08:00:15 UTC
